spring.application.name=biblioteca-ag-backend

# Define o uso do Docker Compose, inicialmente desativado.
spring.docker.compose.enabled=false

# Configurações para conexão com PostgreSQL.
spring.datasource.url=jdbc:postgresql://localhost:5432/db_biblioteca
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true